/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegoandreat;

import javax.swing.JFrame;

/**
 *
 * @author Nanos
 */
public class FrmInstrucciones_UC1 extends javax.swing.JFrame {

    /**
     * Creates new form FrmInstrucciones_UC1
     */
    public FrmInstrucciones_UC1() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(lblFondo_Instrucciones_UC1, "src/Imagenes/Fondo_UC2.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblNiveles_UC1, "src/Imagenes/Instrucciones_1.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblCerrar_UC1, "src/Imagenes/delete.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblMecanicas_UC1, "src/Imagenes/Instrucciones_2.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCerrar_UC1 = new javax.swing.JLabel();
        tbMecanicas_UC1 = new javax.swing.JTabbedPane();
        lblNiveles_UC1 = new javax.swing.JLabel();
        lblMecanicas_UC1 = new javax.swing.JLabel();
        lblFondo_Instrucciones_UC1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(124, 216, 229));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.setLayout(null);

        lblCerrar_UC1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        lblCerrar_UC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar_UC1MouseClicked(evt);
            }
        });
        jPanel2.add(lblCerrar_UC1);
        lblCerrar_UC1.setBounds(610, 10, 60, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 680, 70);

        lblNiveles_UC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbMecanicas_UC1.addTab("Niveles", lblNiveles_UC1);
        tbMecanicas_UC1.addTab("Mecánicas", lblMecanicas_UC1);

        jPanel1.add(tbMecanicas_UC1);
        tbMecanicas_UC1.setBounds(20, 100, 680, 360);

        lblFondo_Instrucciones_UC1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel1.add(lblFondo_Instrucciones_UC1);
        lblFondo_Instrucciones_UC1.setBounds(0, 0, 720, 480);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrar_UC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar_UC1MouseClicked
        FrmMenu_Niveles_UC2 llamar = new FrmMenu_Niveles_UC2();
        llamar.setVisible(true);
        llamar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_lblCerrar_UC1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInstrucciones_UC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInstrucciones_UC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInstrucciones_UC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInstrucciones_UC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInstrucciones_UC1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCerrar_UC1;
    private javax.swing.JLabel lblFondo_Instrucciones_UC1;
    private javax.swing.JLabel lblMecanicas_UC1;
    private javax.swing.JLabel lblNiveles_UC1;
    private javax.swing.JTabbedPane tbMecanicas_UC1;
    // End of variables declaration//GEN-END:variables
}
