/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegoandreat;

/**
 *
 * @author Nanos
 */
public class FrmMenu_Niveles_UC2 extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu_Niveles_UC2
     */
    public FrmMenu_Niveles_UC2() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(jFondo_Label_UC1, "src/juegoandreat/Fondo_UC1.gif");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblCerrar_UC1, "src/Imagenes/fig.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCerrar_UC1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFondo_Label_UC1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nivel Intermedio");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 71, 206), 6));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 220, 420, 80);

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nivel Dificil");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 71, 206), 6));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 340, 420, 80);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Instrucciones");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 71, 206), 6));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 450, 420, 80);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(null);

        lblCerrar_UC1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblCerrar_UC1.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar_UC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar_UC1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 71, 206), 6));
        jPanel1.add(lblCerrar_UC1);
        lblCerrar_UC1.setBounds(410, 10, 60, 50);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 3, 24)); // NOI18N
        jLabel2.setText("Menú de Niveles");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 20, 220, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 70);

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nivel Facil");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 71, 206), 6));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 100, 420, 80);

        jFondo_Label_UC1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jFondo_Label_UC1);
        jFondo_Label_UC1.setBounds(0, 70, 480, 490);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu_Niveles_UC2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu_Niveles_UC2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu_Niveles_UC2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu_Niveles_UC2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu_Niveles_UC2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jFondo_Label_UC1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCerrar_UC1;
    // End of variables declaration//GEN-END:variables
}
