/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegoandreat;

import javax.swing.JFrame;

/**
 *
 * @author 15-CW0001la
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(lblNiveles_UC1, "src/Imagenes/Niveles_UC1.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnTeoria = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        BtnPiano = new javax.swing.JButton();
        btnAutores = new javax.swing.JButton();
        BtnPiano1 = new javax.swing.JButton();
        lblNiveles_UC1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ILearnPiano");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("ILearnPiano");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnTeoria.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnTeoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconfinder-musicmelodysoundaudio17-4105564_113840.png"))); // NOI18N
        btnTeoria.setText("Teoría");
        btnTeoria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTeoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTeoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 190, 50));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 100, 30));

        BtnPiano.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        BtnPiano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pianoicono.png"))); // NOI18N
        BtnPiano.setText("Práctica");
        BtnPiano.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnPiano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPianoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPiano, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, 50));

        btnAutores.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/business_man_usersearch_thesearch_theclient_2356.png"))); // NOI18N
        btnAutores.setText("Autores");
        btnAutores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 190, 50));

        BtnPiano1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        BtnPiano1.setText("Niveles");
        BtnPiano1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnPiano1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPiano1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPiano1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 130, 50));

        lblNiveles_UC1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lblNiveles_UC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNiveles_UC1MouseClicked(evt);
            }
        });
        getContentPane().add(lblNiveles_UC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 232, 60, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gif.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTeoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeoriaActionPerformed
        frmTeoria llamar = new frmTeoria();
        llamar.setVisible(true);
        llamar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_btnTeoriaActionPerformed

    private void BtnPianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPianoActionPerformed
        frmJuegoMain llamar = new frmJuegoMain();
        llamar.setVisible(true);
        llamar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_BtnPianoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresActionPerformed
       frmAutores llamar = new frmAutores();
        llamar.setVisible(true);
        llamar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_btnAutoresActionPerformed

    private void BtnPiano1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPiano1ActionPerformed
        FrmMenu_Niveles_UC2 llamar = new FrmMenu_Niveles_UC2();
        llamar.setVisible(true);
        llamar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_BtnPiano1ActionPerformed

    private void lblNiveles_UC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNiveles_UC1MouseClicked
        FrmMenu_Niveles_UC2 llamar = new FrmMenu_Niveles_UC2();
        llamar.setVisible(true);
        llamar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_lblNiveles_UC1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPiano;
    private javax.swing.JButton BtnPiano1;
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnTeoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNiveles_UC1;
    // End of variables declaration//GEN-END:variables
}
